# Generated by Django 5.2.7 on 2025-10-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('location', models.CharField(help_text='Location where the event will take place', max_length=200)),
                ('start_time', models.DateTimeField(help_text='When the event starts')),
                ('end_time', models.DateTimeField(help_text='When the event ends')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this event was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this event was last updated')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_time'],
            },
        ),
    ]
