# Generated by Django 5.2.7 on 2025-10-03 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('location', models.CharField(help_text='Location where the event will take place', max_length=200)),
                ('start_time', models.DateTimeField(help_text='When the event starts')),
                ('end_time', models.DateTimeField(help_text='When the event ends')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this event was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this event was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this event', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time'], name='events_even_start_t_c2d277_idx'), models.Index(fields=['created_by'], name='events_even_created_95418c_idx'), models.Index(fields=['created_at'], name='events_even_created_52c227_idx')],
            },
        ),
    ]
