# Generated by Django 5.2.7 on 2025-10-06 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='When the user registered for the event')),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the user', null=True)),
                ('event', models.ForeignKey(help_text='The event being registered for', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(help_text='The user registering for the event', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.ManyToManyField(blank=True, help_text='Users registered for this event', related_name='registered_events', through='events.EventRegistration', to=settings.AUTH_USER_MODEL),
        ),
    ]
