# Generated by Django 5.2.7 on 2025-10-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration_event_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registrations',
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
