# Generated by Django 5.2.7 on 2025-10-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(help_text="Action that triggered the notification (e.g., 'uploaded a resource', 'posted in forum')", max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the target object', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read by the recipient')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was created')),
                ('notification_type', models.CharField(choices=[('resource', 'Resource'), ('event', 'Event'), ('forum', 'Forum'), ('user', 'User'), ('system', 'System'), ('other', 'Other')], default='other', help_text='Type of notification for categorization', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification (JSON format)')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
