# Generated by Django 5.2.7 on 2025-10-04 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(help_text="Action that triggered the notification (e.g., 'uploaded a resource', 'posted in forum')", max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the target object', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read by the recipient')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was created')),
                ('notification_type', models.CharField(choices=[('resource', 'Resource'), ('event', 'Event'), ('forum', 'Forum'), ('user', 'User'), ('system', 'System'), ('other', 'Other')], default='other', help_text='Type of notification for categorization', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification (JSON format)')),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this notification (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of the target object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx')],
            },
        ),
    ]
