# Generated by Django 5.2.7 on 2025-10-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('resource', 'Resource'), ('event', 'Event'), ('forum', 'Forum'), ('user', 'User'), ('chat', 'Chat'), ('system', 'System'), ('other', 'Other')], default='other', help_text='Type of notification for categorization', max_length=50),
        ),
    ]
