# Generated by Django 5.2.7 on 2025-10-21 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private reply (only visible to sender and recipient)'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, help_text='Emoji reactions with user IDs'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='notifications.chatmessage'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('reply', 'Reply'), ('system', 'System'), ('join', 'User Join'), ('leave', 'User Leave')], default='text', max_length=20),
        ),
    ]
