# Generated by Django 5.2.7 on 2025-10-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_privatechatroom_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio file for voice messages', null=True, upload_to='voice_messages/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration of voice message in seconds', null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio file for voice messages', null=True, upload_to='private_voice_messages/'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration of voice message in seconds', null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice Message'), ('system', 'System')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, help_text='Message content'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('reply', 'Reply'), ('system', 'System'), ('join', 'User Join'), ('leave', 'User Leave'), ('voice', 'Voice Message')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='message',
            field=models.TextField(blank=True, help_text='Private message content'),
        ),
    ]
