# Generated by Django 5.2.7 on 2025-10-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_add_voice_message_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_attachment',
            field=models.FileField(blank=True, help_text='File attachment', null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_type',
            field=models.CharField(blank=True, choices=[('media', 'Media'), ('document', 'Document')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='file_attachment',
            field=models.FileField(blank=True, help_text='File attachment', null=True, upload_to='private_chat_files/'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='file_type',
            field=models.CharField(blank=True, choices=[('media', 'Media'), ('document', 'Document')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('reply', 'Reply'), ('system', 'System'), ('join', 'User Join'), ('leave', 'User Leave'), ('voice', 'Voice Message'), ('file', 'File Attachment')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice Message'), ('file', 'File Attachment'), ('system', 'System')], default='text', max_length=20),
        ),
    ]
