# Generated by Django 5.2.7 on 2025-10-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_participants',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
