# Generated by Django 5.2.7 on 2025-10-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('class', 'Class Room'), ('study_group', 'Study Group'), ('discussion', 'Discussion'), ('project', 'Project Room')], default='class', max_length=20),
        ),
    ]