# Generated by Django 5.2.7 on 2025-10-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
    ]
