# Generated by Django 5.2.7 on 2025-10-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_allow_file_uploads_room_allow_voice_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allow_file_uploads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='allow_voice_messages',
            field=models.BooleanField(default=True),
        ),
    ]
