# Generated by Django 5.2.7 on 2025-10-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_room_allow_file_uploads_room_allow_voice_messages'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS chat_joinrequest CASCADE;
            """,
            reverse_sql="""
            -- This is irreversible
            """
        ),
        migrations.RunSQL(
            """
            CREATE TABLE chat_joinrequest (
                id SERIAL PRIMARY KEY,
                status VARCHAR(20) NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                room_id INTEGER NOT NULL REFERENCES chat_room(id) ON DELETE CASCADE,
                requester_id INTEGER NOT NULL REFERENCES users_user(id) ON DELETE CASCADE,
                UNIQUE(room_id, requester_id)
            );
            
            CREATE INDEX chat_joinrequest_room_id_idx ON chat_joinrequest(room_id);
            CREATE INDEX chat_joinrequest_requester_id_idx ON chat_joinrequest(requester_id);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS chat_joinrequest CASCADE;
            """
        ),
    ]
