# Generated by Django 5.2.7 on 2025-10-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
        migrations.AddField(
            model_name='resource',
            name='form_level',
            field=models.CharField(choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4')], default='form1', help_text='Form level for which this resource is intended', max_length=10),
        ),
    ]
