# Generated by Django 5.2.7 on 2025-10-06 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the student', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the student', max_length=254)),
                ('username', models.CharField(help_text='Username of the student', max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Gender of the student', max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth of the student', null=True)),
                ('bio', models.TextField(blank=True, help_text='Short biography or description of the student', max_length=500, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture of the student', null=True, upload_to='profile_pics/')),
                ('department', models.CharField(help_text='Department or field of study', max_length=100)),
                ('year_of_study', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year'), (5, 'Fifth Year'), (6, 'Sixth Year')], help_text='Current year of study', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('contact', models.CharField(blank=True, help_text='Contact number of the student', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this profile was last updated')),
                ('user', models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
