# Generated by Django 5.2.7 on 2025-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_number',
            field=models.CharField(blank=True, help_text='Student admission number (for students only)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Primary department (for teachers only)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department_secondary',
            field=models.CharField(blank=True, help_text='Secondary department (for teachers only)', max_length=100, null=True),
        ),
    ]
